### ISSUE TITLE
it wont show up 

### ISSUE THREAD

**Issue by Darenmcurtis** [Astropilot/ValheimTooler#33] opened 2023-08-25 21:08 UTC
it wont show up when i press the button

**Comment by Astropilot** [comment] 2023-08-25 21:52
Hi @Darenmcurtis ,
ValheimTooler is not working currently for the new update of the game (ref. https://github.com/Astropilot/ValheimTooler/issues/27#issuecomment-1693549546). I'm working on an update that should come in a few days.
I'm closing this issue as the problem is already reported on the issue #27

**Closed by Astropilot** 2023-08-25 21:52 UTC
